### ISSUE TITLE
Hey wanna use yarn workspace ?

### ISSUE THREAD

**Issue by douglasduteil** [paulsouche/ng-on-rest#1]
<img src=https://user-images.githubusercontent.com/730511/35892895-c17946a6-0bab-11e8-80d3-393db5e240aa.gif width=693>

---

Hello @paulsouche 

What do you thnik about using yarn workspace to handle the dependencies of your monorepo ;)
You can get ride [this verbose list of dependencies](https://github.com/paulsouche/ng-on-rest/blob/5fe9ca9089a2d82f2ec60e89619a9a4b12945073/package.json#L31-L99) with it ;)

**Comment by paulsouche** [comment]
Did already try but had some issues with symbolics links and how deps are resolved in workspace

**Comment by douglasduteil** [comment]
True that handling dependencies can be tricky... especially for peerDependencies.
I naively try it too, and it's popping warnings everywhere...
